### ISSUE TITLE
Create Conda-Forge Package for Intake-odbc

### ISSUE THREAD

**Issue by rxm7706** [intake/intake-odbc#9]
Intake-odbc is not available on PyPi ; if we can package it for pip install, we could publish intake-odbc to conda-forge too. Its currently only available on intake channel.

**Comment by blakerosenthal** [comment]
I would be happy to :)

**Comment by rxm7706** [comment]
@blakerosenthal thank you.
Draft PR to publish to conda-forge for your review.
I have kept you and @martindurant as maintainers. 
https://github.com/conda-forge/staged-recipes/pull/22610
If the PR looks good, please comment to confirm being added as maintainers, I will move the PR from Draft to Ready for review.

**Comment by rxm7706** [comment]
Closing as Completed via https://github.com/conda-forge/staged-recipes/pull/22610
Conda Package is available at 
https://anaconda.org/conda-forge/intake-odbc
